basic:
  seed: 233
  GPU: 0
  debug: False
  id: 'unnamed'
  mode: train
  search: False
  amp: 'Native'

experiment:
  name: 'AnnotatedRandomKTrainTestSplit'
  random_state: 233
  run_fold: -1
  batch_sampler: False
  weight: False
  preprocess: JPEG_512_pan
  image_only: True
  skip_outlier: True
  outlier: train
  anno_only: False
  keep_valid: True

data:
  image_prefix: 'jpeg_512'
  mask_prefix: 'masks_v1'
  full_mask: False
  csv: 'gkf.csv'
  N: 14

model:
  name: 'pvt2_b3_unete'
  from_checkpoint: '/home/ps/data/sheep/notebook/seg_model/4_classes_pvt2_b3_pretrained.pth'
  out_feature: 2
  params:
    dropout: 0.5
    pretrained: True
    pool: gem

train:
  dir: '../results'
  batch_size: 3
  num_epochs: 30
  cutmix: False
  beta: 1
  cutmix_prob: 0.5
  cutmix_prob_increase: 0
  validations_round: 1
  freeze_backbond: 0
  freeze_top_layer_groups: 0
  freeze_start_epoch: 0

eval:
  batch_size: 8

loss:
  name: 'bce'
  seg_weight: 20
  params:
#    eps: 0.1
    reduction: 'none'

optimizer:
  name: 'Adam'
  step: 1
  params:
    lr: 0.0004
    weight_decay: 0

scheduler:
  name: 'CosineAnnealingLR'
  warm_up: True
  params:
    factor: 0.2
    patience: 10

transform:
  name: 's_0220/naive'
  val_name: 's_0220/resize_384'
  num_preprocessor: 4
  size: 384
