__version__: 1.3.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: Resize
    always_apply: false
    height: 384
    interpolation: 1
    p: 1
    width: 384
  - __class_fullname__: HorizontalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: VerticalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: Transpose
    always_apply: false
    p: 0.5
  - __class_fullname__: RandomBrightness
    always_apply: false
    limit:
    - -0.1
    - 0.1
    p: 0.7
  - __class_fullname__: ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: null
    p: 0.7
    rotate_limit:
    - -45
    - 45
    rotate_method: largest_box
#    scale_limit:
#    - -0.30000000000000004
#    - 0.30000000000000004
#    shift_limit_x:
#    - -0.3
#    - 0.3
#    shift_limit_y:
#    - -0.3
#    - 0.3
    value: null
